#!/usr/bin/env python
"""
Recovery Tool for Failed Power Grid Simulation Scenarios.

This module provides utilities for analyzing, diagnosing, and recovering from
failed simulation runs in the power grid scenario generation pipeline. It helps
identify which scenarios failed, why they failed, and provides mechanisms to
retry only the failed scenarios without re-running the entire simulation.

Features
--------
- Analyze simulation logs to identify failed scenarios
- Group failures by fault location for pattern identification
- Verify data file integrity (detect corrupted or incomplete files)
- Generate retry scripts for failed scenarios only
- Export failed scenario lists for manual inspection

Usage
-----
Run interactively to analyze and recover from simulation failures::

    $ python recovery_tool.py

The tool will present a menu with recovery options after analyzing the
current simulation state.

Workflow
--------
1. Run your main simulation (generate_scenarios.py)
2. If failures occur, run this recovery tool
3. Analyze the failure patterns
4. Generate a retry script or export failed scenarios
5. Re-run only the failed scenarios with adjusted parameters

Required Files
--------------
- simulation_log.json : Log file from the main simulation containing
  scenario outcomes with 'diverged' and 'fault_location' fields.
- scenario_metadata.json : Original metadata file with scenario parameters
  (required for generating retry scripts).

Output Files
------------
- retry_metadata.json : Metadata for failed scenarios only
- retry_failed.py : Executable script to retry failed scenarios
- failed_scenarios.json : JSON export of failed scenario details

Environment Variables
---------------------
The script sets the following environment variables to prevent thread
contention when running with parallel processing:

- OMP_NUM_THREADS=1
- MKL_NUM_THREADS=1
- OPENBLAS_NUM_THREADS=1
- NUMEXPR_NUM_THREADS=1

Dependencies
------------
- scripts.run.generate_scenarios : Main simulation driver functions

Notes
-----
- The retry script uses conservative settings (single job, smaller batches)
  to improve success rate for problematic scenarios.
- Scenarios are considered "failed" if they diverged OR have no output file.
- Small files (<1KB) are flagged as potentially corrupted during integrity checks.

See Also
--------
- generate_scenarios.py : Main simulation script
- monitor.py : Real-time simulation monitoring

Example
-------
Typical recovery workflow::

    $ python recovery_tool.py
    
    Power Grid Simulation Recovery Tool
    ========================================
    
    === Simulation Status ===
    Total scenarios: 10000
    Succeeded: 9850 (98.5%)
    Failed: 150 (1.5%)
    ...
    
    === Recovery Options ===
    1. Create retry script for failed scenarios
    2. Export failed scenario list
    3. Exit
    
    Select option (1-3): 1
"""

import json
import sys
import os

# -----------------------------------------------------------------------------
# Environment Configuration
# -----------------------------------------------------------------------------
# Disable multi-threading in numerical libraries to prevent thread contention
# when running multiple simulation processes in parallel. Each process should
# use a single thread to avoid oversubscription of CPU cores.
os.environ["OMP_NUM_THREADS"] = "1"      # OpenMP (used by many compiled libs)
os.environ["MKL_NUM_THREADS"] = "1"      # Intel Math Kernel Library
os.environ["OPENBLAS_NUM_THREADS"] = "1" # OpenBLAS linear algebra library
os.environ["NUMEXPR_NUM_THREADS"] = "1"  # NumExpr expression evaluator

from pathlib import Path

# Add current directory to path for local imports
sys.path.insert(0, '.')

# Import simulation driver from the main generation script
from scripts.run.generate_scenarios import run_simulation_driver_batched


def analyze_simulation_log(log_file="simulation_log.json"):
    """
    Analyze the simulation log to identify and categorize failed scenarios.

    Reads the simulation log file and computes statistics on scenario outcomes,
    including success/failure rates and grouping failures by fault location
    to identify problematic buses.

    Parameters
    ----------
    log_file : str, default='simulation_log.json'
        Path to the JSON log file generated by the simulation. Expected format
        is a dictionary mapping scenario IDs to result dictionaries containing
        'diverged' (bool) and 'fault_location' (int/str) keys.

    Returns
    -------
    tuple of (dict, dict) or None
        - log : dict
            The complete simulation log dictionary.
        - failed_scenarios : dict
            Subset of log containing only failed scenarios (diverged=True
            or missing output file).
        
        Returns None if the log file doesn't exist.

    Examples
    --------
    >>> log, failed = analyze_simulation_log('my_simulation.json')
    >>> print(f"Failed scenarios: {len(failed)}")
    """
    # Verify log file exists
    if not os.path.exists(log_file):
        print(f"Error: {log_file} not found")
        return None

    # Load and parse the log file
    with open(log_file, 'r') as f:
        log = json.load(f)

    # Calculate summary statistics
    total = len(log)
    succeeded = sum(1 for s in log.values() if not s.get('diverged', True))
    failed = sum(1 for s in log.values() if s.get('diverged', True))
    missing_files = sum(1 for s in log.values() if s.get('file') is None)

    # Display status summary
    print(f"\n=== Simulation Status ===")
    print(f"Total scenarios: {total}")
    print(f"Succeeded: {succeeded} ({succeeded/total*100:.1f}%)")
    print(f"Failed: {failed} ({failed/total*100:.1f}%)")
    print(f"Missing files: {missing_files}")

    # Identify all failed scenarios (diverged OR missing output file)
    failed_scenarios = {
        sid: info for sid, info in log.items()
        if info.get('diverged', True) or info.get('file') is None
    }

    # Group failures by fault location for pattern analysis
    if failed_scenarios:
        print(f"\nFailed scenario IDs: {len(failed_scenarios)}")

        by_fault = {}
        for sid, info in failed_scenarios.items():
            floc = info.get('fault_location', 'unknown')
            if floc not in by_fault:
                by_fault[floc] = []
            by_fault[floc].append(sid)

        # Display failure distribution (helps identify problematic buses)
        print("\nFailed scenarios by fault location:")
        for floc in sorted(by_fault.keys()):
            if floc != 'unknown':
                print(f"  Fault location {floc}: {len(by_fault[floc])} failures")

    return log, failed_scenarios


def create_retry_script(failed_scenarios, metadata_file="scenario_metadata.json"):
    """
    Generate a retry script and metadata for failed scenarios only.

    Creates two files:
    1. A JSON file containing metadata for only the failed scenarios
    2. An executable Python script configured to retry those scenarios
       with more conservative simulation parameters.

    Parameters
    ----------
    failed_scenarios : dict
        Dictionary mapping scenario IDs to their failure information,
        as returned by analyze_simulation_log().
    metadata_file : str, default='scenario_metadata.json'
        Path to the original scenario metadata file containing parameters
        for all scenarios. Each failed scenario ID must exist in this file.

    Returns
    -------
    None
        Creates 'retry_metadata.json' and 'retry_failed.py' files.

    Notes
    -----
    The generated retry script uses conservative settings:
    - n_jobs=1 : Single process to avoid MPI/parallelization issues
    - batch_size=3 : Smaller batches for better error isolation
    - checkpoint_interval=10 : Frequent checkpoints to preserve progress

    Warnings
    --------
    The current implementation has an incomplete retry script generation.
    The retry_script variable is initialized but not fully populated.
    This is marked as a TODO for future development.
    """
    if not failed_scenarios:
        print("No failed scenarios to retry")
        return

    # Load the original metadata containing all scenario parameters
    with open(metadata_file, 'r') as f:
        all_metadata = json.load(f)

    # Extract metadata for only the failed scenarios
    retry_metadata = {sid: all_metadata[sid] for sid in failed_scenarios.keys()}

    # Save filtered metadata for retry
    retry_metadata_file = "retry_metadata.json"
    with open(retry_metadata_file, 'w') as f:
        json.dump(retry_metadata, f, indent=4)

    print(f"\nCreated {retry_metadata_file} with {len(retry_metadata)} scenarios to retry")

    # TODO: Complete the retry script generation
    # Currently only initializes the shebang line
    retry_script = "#!/usr/bin/env python"


def retry_failed_scenarios():
    """
    Execute retry of previously failed scenarios with conservative settings.

    Loads the retry metadata file (generated by create_retry_script) and
    runs the simulation driver with adjusted parameters designed to improve
    success rate for problematic scenarios.

    The function uses:
    - Single-threaded execution (n_jobs=1) to avoid parallelization issues
    - Smaller batch sizes for better error isolation
    - More frequent checkpoints to preserve progress

    Returns
    -------
    None
        Runs simulations and updates log/data files in place.

    Raises
    ------
    FileNotFoundError
        If retry_metadata.json doesn't exist.

    Notes
    -----
    The PowerGridModel selection is currently hardcoded to 'ACTIVSg500'.
    This should be made configurable via command-line argument or
    read from a configuration file.

    See Also
    --------
    create_retry_script : Generates the retry_metadata.json file
    run_simulation_driver_batched : Main simulation driver function
    """
    # TODO: Make model selection dynamic (via config file or CLI argument)
    PowerGridModel = "ACTIVSg500"

    # Select data files based on power grid model
    if PowerGridModel == "ACTIVSg500":
        raw = "data/ACTIVSg500.raw"
        dyr = "data/ACTIVSg500.dyr"
    # TODO: Add support for other models:
    # elif PowerGridModel == "OtherModel":
    #     raw = "data/OtherModel.raw"
    #     dyr = "data/OtherModel.dyr"

    # Load metadata for scenarios that need to be retried
    with open("retry_metadata.json", 'r') as f:
        retry_metadata = json.load(f)

    print(f"Retrying {len(retry_metadata)} failed scenarios...")

    # Run with conservative settings to maximize success rate
    run_simulation_driver_batched(
        raw, dyr, retry_metadata,
        noise_type="normal",
        noise_var=0.25,
        balance_generation=True,
        n_jobs=1,           # Single job to avoid MPI/parallelization issues
        batch_size=3,       # Smaller batches for better error isolation
        checkpoint_interval=10  # Frequent checkpoints
    )


def check_data_integrity():
    """
    Verify integrity of simulation output data files.

    Scans the simulation_data directory for .npz files and checks for
    potential issues such as missing or suspiciously small files that
    may indicate incomplete or corrupted writes.

    Returns
    -------
    None
        Prints diagnostic information to stdout.

    Warnings
    --------
    Files smaller than 1KB are flagged as potentially corrupted,
    as valid simulation output typically exceeds this size.

    Notes
    -----
    This function performs basic size-based validation only. For more
    thorough validation, consider loading each .npz file and verifying
    expected arrays are present and have correct shapes.
    """
    data_dir = Path("simulation_data")

    if not data_dir.exists():
        print("Warning: simulation_data directory not found")
        return

    # Find all scenario data files
    data_files = list(data_dir.glob("scenario_*.npz"))
    print(f"\nFound {len(data_files)} data files in {data_dir}")

    # Check for suspiciously small files (likely corrupted or incomplete)
    small_files = []
    for f in data_files:
        size = f.stat().st_size
        if size < 1000:  # Less than 1KB is suspicious for simulation data
            small_files.append(f)

    if small_files:
        print(f"Warning: {len(small_files)} files are suspiciously small (<1KB)")
        # Optionally list the small files for investigation
        # for f in small_files[:10]:  # Show first 10
        #     print(f"  - {f.name}: {f.stat().st_size} bytes")


def main():
    """
    Main entry point for the interactive recovery tool.

    Provides a menu-driven interface for analyzing simulation status,
    checking data integrity, and initiating recovery operations.

    The workflow:
    1. Analyze simulation log to identify failures
    2. Check data file integrity
    3. Present recovery options to the user
    4. Execute selected recovery action

    Returns
    -------
    None
    """
    print("Power Grid Simulation Recovery Tool")
    print("=" * 40)

    # Step 1: Analyze current simulation status
    result = analyze_simulation_log()

    if result is None:
        return

    log, failed = result

    # Step 2: Check data file integrity
    check_data_integrity()

    # Step 3: Present recovery options if there are failures
    if failed:
        print("\n=== Recovery Options ===")
        print("1. Create retry script for failed scenarios")
        print("2. Export failed scenario list")
        print("3. Exit")

        choice = input("\nSelect option (1-3): ").strip()

        if choice == '1':
            create_retry_script(failed)
        elif choice == '2':
            # Export failed scenarios for external analysis or manual retry
            with open("failed_scenarios.json", 'w') as f:
                json.dump(failed, f, indent=4)
            print(f"Exported failed scenarios to failed_scenarios.json")
        # choice == '3' or invalid input: exit silently
    else:
        print("\nAll scenarios completed successfully!")


# =============================================================================
# Script Entry Point
# =============================================================================
# NOTE: There appear to be two intended entry points in the original code:
# 1. main() - Interactive menu-driven recovery
# 2. retry_failed_scenarios() - Direct retry execution
#
# The current implementation runs main() for interactive use.
# To run retry directly, call: python -c "from recovery_tool import retry_failed_scenarios; retry_failed_scenarios()"

if __name__ == "__main__":
    main()
